version: '3'
services:
  postfix:
    image: postfix:latest
    container_name: postfix
    ports:
      - "25:25"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /var/log/maillog:/var/log/maillog
    healthcheck:
      test: "nc -vz 127.0.0.1 25"
    restart: always

