#!/usr/bin/env bash

if [ ! -f docker-rebuild/rebuild.sh ]; then
    echo -e "Updating git submodules...\n"
    git submodule init
    git submodule update
    git -C docker-rebuild checkout main
fi

echo -e "Checking if 'docker-rebuild' submodule is up-to-date...\n"
git -C docker-rebuild pull

docker-rebuild/rebuild.sh

if [ ! -f /var/log/maillog ]; then
    echo -e "Calling 'sudo touch' to create /var/log/maillog file ...\n"
    sudo touch /var/log/maillog
fi
